---
# params:
#  snapshot_name: ex: initial
#  snapshot_action: ex: Take
#
- name: baseline snapshot
  uri:
    url: "{{api_dstu2_server_external_url}}/{{api_dstu2_server_sandbox}}/sandbox/snapshot/{{snapshot_name}}"
    method: POST
    body: '{"action": "{{snapshot_action}}"}'
    body_format: json
    HEADER_Content-Type: "application/json"
    validate_certs: no
    timeout: 90