- name: install prerequisite packages for jekyll
  tags: [general]
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: pkg={{item}} force=yes
  with_items:
         - ruby-dev
         - nodejs
         - nodejs-legacy
         - npm
         - zlibc
         - zlib1g
         - zlib1g-dev

- name: install jekyll
  tags: [general]
  gem: name={{item}} state=latest user_install=no
  with_items:
         - github-pages
         - redcarpet

- name: checkout docs
  tags: [docs,docs-rebuild]
  become_user: "{{username}}"
  git: repo={{docs_server_repo}}
       version={{docs_server_branch}}
       dest={{install_dir}}/docs/repo
       update={{update_repositories}}
  register: docs_checkout

- name: delete static directory
  tags: [docs,docs-rebuild]
  file: path={{install_dir}}/docs/static state=absent

- name: create static directory
  tags: [docs,docs-rebuild]
  become_user: "{{username}}"
  file: path={{install_dir}}/docs/static state=directory

- name: generate self-signed ssl certificate (docs server)
  tags: [docs]
  when: docs_server_secure_http and not use_custom_ssl_certificates
  shell: creates=/etc/nginx/ssl/docs.crt
         /bin/echo -e "{{docs_server_ssl_country}}\n{{docs_server_ssl_province}}\n{{docs_server_ssl_locality}}\n{{docs_server_ssl_organization}}\n{{docs_server_ssl_division}}\n{{docs_server_host}}\n{{docs_server_ssl_email}}\n" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/docs.key -out /etc/nginx/ssl/docs.crt

- name: configure nginx (docs)
  tags: [docs,nginx]
  template: src=nginx_docs.j2 dest=/etc/nginx/sites-enabled/docs owner=root group=root mode=0644
  notify:
        - restart nginx

- meta: flush_handlers
