---
auth_server_initial_memory: 128M
auth_server_max_memory: 256M

# Version control information
auth_branch: "develop"
# reference-auth-server-webapp is cloned to gain the SQL install files
auth_webapp_project: "reference-auth-server-webapp"
# reference-auth-server-webapp is cloned to gain the sourcecode to build the application
auth_webapp_ldap_project: "reference-auth-server-ldap-webapp"

# Database schema
auth_server_database: oic
auth_db_file: "{{install_dir}}/auth_server_db.hsql"

auth_server_newUserUrl: "{{pwm_server_url}}public/newuser"
auth_server_forgotPasswordUrl: "{{pwm_server_url}}public/forgottenpassword"
persona_auth_server_newUserUrl: "{{pwm_server_url}}public/newuser"
persona_auth_server_forgotPasswordUrl: "{{pwm_server_url}}public/forgottenpassword"