---
# sandman artifact
sandman_server_artifact_group_id: "org.hspconsortium.sandbox"
sandman_server_artifact_artifact_id: "hspc-sandbox-manager"
# until 1.7.1 is available
sandman_server_artifact_version: "1.7.2"
sandman_server_artifact_packaging: "war"
sandman_server_artifact_repository_url: "{{snapshot_repository_url}}"
sandman_server_database: "sandman"
sandman_server_internal_port: "8080"
sandman_server_external_url: "{{'https' if use_secure_http else 'http'}}://{{sandman_server_external_host}}{{(':'+sandman_server_external_port|string) if sandman_server_external_port|int not in (80,443) else ''}}"
sandman_server_env: "prod"
sandman_server_default_sandbox_creator_roles: "ADMIN,MANAGE_USERS,MANAGE_DATA"
sandman_server_default_system_roles: "USER"
sandman_server_default_private_sandbox_roles: "USER,MANAGE_USERS,MANAGE_DATA"
sandman_server_default_sandbox_visibility: "PUBLIC"
sandman_server_default_public_sandbox_roles: "USER"
sandbox_server_admin_access_client_id: "sandman_admin"
sandman_server_api_v1_url: "{{api_dstu2_server_external_url}}"
sandman_server_api_v2_url: "{{api_stu3_server_external_url}}"
sandman_server_api_v3_url: "{{api_stu3_server_external_url}}"
sandman_server_api_v4_url: "{{api_stu3_server_external_url}}"
sandman_company_logo_path: "static/branding/smart/images/smart-logo.png"
sandman_company_logo2x_path: "static/branding/smart/images/smart-logo@2x.png"
