---
# Generic Service Template
# params:
#   service_name: name of the service
#   database: schema associated with the service
#   database_drop: true to drop the database, false otherwise
#   database_exists: true to make sure a database exists, false otherwise
#   service_definition_file: service definition file
#   gateway_definition_file: nginx gateway definition file
#   internal_port: internal port
#   external_host: external hostname
#   external_port: external port
#   health_check_url: optional health_check url

- name: "stop {{service_name}}"
  service:
    name: "{{service_name}}"
    state: "stopped"
  ignore_errors: yes

- name: "drop the {{database}} database"
  when: database is defined and database_drop is defined and database_drop
  mysql_db:
    name: "{{database}}"
    state: absent
  ignore_errors: yes

- name: "create the {{database}} database"
  when: database is defined and database_exists is defined and database_exists
  mysql_db:
    name: "{{database}}"
    state: present
  ignore_errors: yes

- name: "configure {{service_name}} service"
  when: service_definition_file is defined
  template:
    src: "{{service_definition_file}}"
    dest: "/etc/systemd/system/{{service_name}}.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "enable {{service_name}} service"
  when: service_definition_file is defined
  shell: "systemctl enable {{service_name}}.service"

- name: "reload systemd daemon"
  when: service_definition_file is defined
  shell: "systemctl daemon-reload"

- name: "start {{service_name}}"
  when: service_definition_file is defined
  service:
    name: "{{service_name}}"
    state: "started"

- name: "verify {{service_name}} is available internally at localhost:{{internal_port}}"
  when: service_definition_file is defined
  become_user: "{{hosting_username}}"
  wait_for:
    host: "localhost"
    port: "{{internal_port}}"

- name: "configure nginx ({{service_name}})"
  when: gateway_definition_file is defined
  template:
    src: "{{gateway_definition_file}}"
    dest: "{{nginx_home}}/sites-enabled/{{service_name}}"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "restart nginx"
  when: gateway_definition_file is defined
  service:
    name: "nginx"
    state: "restarted"

- name: "verify {{service_name}} is available externally at {{external_host}}:{{external_port}}"
  when: external_host is defined and health_check_url is undefined
  become_user: "{{hosting_username}}"
  wait_for:
    host: "{{external_host}}"
    port: "{{external_port}}"

- name: "verify {{service_name}} is available externally at {{health_check_url}}"
  when: health_check_url is defined
  command: "curl --silent {{health_check_url}}"
  register: result
  until: result.stdout.find("OK") != -1
  retries: 60
  delay: 1
  changed_when: false
