---
- hosts: all:!REMOTEHOST
  become: yes
  vars_files:
    - settings.yml
    - custom_settings.yml
  roles:
    - common
    - sandman

- hosts: REMOTEHOST
  remote_user: "{{installer_user}}"
  gather_facts: yes
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
  become: yes
  vars_files:
    - settings.yml
    - custom_settings.yml
  roles:
    - common
    - sandman
