---
# *** Main configuration file for the SMART-on-FHIR Installer ***

# To customize the SMART-on-FHIR stack, you can either edit the settings directly in
# this file or set up custom settings overrides (such as custom_settings.yml)

ansible_user_home: "/home/{ansible_user}"

# The user account that will host the servers. If a user account of this name
# already exists on the system, the installer will not alter its credentials or
# authentication mechanism. If you need to set up actual password authentication,
# userpass needs to be a valid SHA-512 hash.
hosting_username: "fhir"
hosting_userpass: "nopass"
hosting_user_home: "/home/{{hosting_username}}"
hosting_user_aws_config_home: "{{hosting_user_home}}/.aws"
hosting_user_jobs_home: "{{hosting_user_home}}/jobs"
hosting_user_jobs_output_home: "{{hosting_user_jobs_home}}/output"
hosting_user_scripts_home: "{{hosting_user_home}}/scripts"

# Settigs for Jetty and Oracle Java. You probably won't have to alter these
# unles you are switching to a different version of Jetty or Java
java_home: "/usr/lib/jvm/java-8-openjdk-amd64/jre"

top_level_domain: "org"
second_level_domain: "smarthealthit"
additional_subdomains: ""
domain_name: "{{second_level_domain}}.{{top_level_domain}}"
full_domain_name: "{{additional_subdomains}}{{domain_name}}"

# Artifact Repositories
m2_repo_folder: "{{hosting_user_home}}/.m2/repository"
snapshot_repository_url: "https://oss.sonatype.org/content/repositories/snapshots"
release_repository_url: "https://repo1.maven.org/maven2/"
smart_repo_base: "https://github.com/smart-on-fhir"
hspc_repo_base: "https://bitbucket.org/hspconsortium"
# By default Ansible will update the local copies of the servers code from
# the source repositories. Set this to "no" if you would rather not have the
# repositories updated on each run.
update_repositories: "yes"

# jetty_runner Artifact
jetty_runner_artifact_group_id: "org.eclipse.jetty"
jetty_runner_artifact_artifact_id: "jetty-runner"
jetty_runner_artifact_version: "9.3.6.v20151106"
jetty_runner_artifact_packaging: "jar"
jetty_runner_artifact_repository_url: "{{release_repository_url}}"
jetty_runner_artifact_location: "{{m2_repo_folder}}/org/hspconsortium/reference/{{api_server_artifact_artifact_id}}/{{api_server_artifact_version}}/{{api_server_artifact_artifact_id}}-{{api_server_artifact_version}}.{{api_server_artifact_packaging}}"

# Controls whether HTTP requests on port 80 will be
# redirected to the server's base URLs
http_redirect: true

# Maximum size of sample patient data files
max_upload_size: "5M"

# When setting up SSL security for the various services, these settings will allow you to
# specify your own certificates instead of using self-signed certificates.
# See files/sample-certificates for the names of the certificate files expected by the script
use_custom_ssl_certificates: false

# Self-signed SSL certificates settings (if generating self-signed certificates)
self_signed_certificate_ssl_country: "US"
self_signed_certificate_ssl_province: "MA"
self_signed_certificate_ssl_locality: "Boston"
self_signed_certificate_ssl_organization: "Example Company"
self_signed_certificate_ssl_division: "support"
self_signed_certificate_ssl_email: "support@{{domain_name}}"

# database configuration
mysql_username: "fhir"
mysql_host: "localhost"
mysql_port: 3306
mysql_privilage: "*.*:ALL,GRANT"
mysql_connect_host: "%"

#custom_ssl_certificates_path: examples/certificates
certificate_truststore_alias: "smart"

