---
# apacheds server configuration
apacheds_server_external_port: "10389"
apacheds_server_external_url: "ldap://{{apacheds_server_external_host}}:{{apacheds_server_external_port}}"
apacheds_server_base: "dc={{second_level_domain}},dc={{top_level_domain}}"
apacheds_server_initial_memory: 128M
apacheds_server_max_memory: 256M
apacheds_server_max_perm_memory: 128M
apacheds_version: "apacheds-2.0.0-M23"
apacheds_artifact_name: "{{apacheds_version}}.tar.gz"
apacheds_home: "{{hosting_user_home}}/{{apacheds_version}}"
apacheds_artifact_url: "http://mirrors.sonic.net/apache//directory/apacheds/dist/2.0.0-M23/{{apacheds_artifact_name}}"
apacheds_server_internal_host: "{{apacheds_server_external_host}}"
apacheds_server_internal_port: "{{apacheds_server_external_port}}"
apacheds_server_system_admin: "admin"
apacheds_server_system_admin_dn: "uid={{apacheds_server_system_admin}},ou=system"
# note, this does not change the password in the apache_ds system
# the apacheds admin password is already set in the apacheds-2.0.0-M23-configured.tar
# if you would like a different password, change it in ApacheDS after deploy
# then change it here for other services to use
apacheds_server_system_admin_initial_password: "secret"
# if you are changing the ldap password after install, set this to the future password
# so the services can be configured to use it correctly
apacheds_server_sandbox_admin: "admin"
apacheds_server_sandbox_admins_ou: "ou=admins"
apacheds_server_sandbox_admins_context: "{{apacheds_server_sandbox_admins_ou}},{{apacheds_server_base}}"
apacheds_server_sandbox_admin_cn: "cn={{apacheds_server_sandbox_admin}}"
apacheds_server_sandbox_admin_dn: "{{apacheds_server_sandbox_admin_cn}},{{apacheds_server_sandbox_admins_context}}"
apacheds_server_sandbox_demo: "demo"
apacheds_server_sandbox_demo_cn: "cn={{apacheds_server_sandbox_demo}}"
apacheds_server_sandbox_demo_dn: "{{apacheds_server_sandbox_demo_cn}},{{apacheds_server_sandbox_admins_context}}"
apacheds_server_sandbox_demo_password: "demo"
apacheds_server_sandbox_users_ou: "ou=users"
apacheds_server_sandbox_users_context: "{{apacheds_server_sandbox_users_ou}},{{apacheds_server_base}}"
apacheds_server_sandbox_test_cn: "cn=test"
apacheds_server_sandbox_test_dn: "{{apacheds_server_sandbox_test_cn}},{{apacheds_server_sandbox_users_context}}"
