---
# *** Main configuration file for the ApacheDS Installer ***
apacheds_server_initial_memory: 128M
apacheds_server_max_memory: 256M

# Repositories
apacheds_version: "apacheds-2.0.0-M23"
apacheds_artifact_name: "{{apacheds_version}}.tar.gz"
apacheds_home: "{{install_dir}}/{{apacheds_version}}"
apacheds_artifact_url: "http://mirrors.sonic.net/apache//directory/apacheds/dist/2.0.0-M23/{{apacheds_artifact_name}}"

# Host
apacheds_server_internal_host: "{{apacheds_server_host}}"
apacheds_server_internal_port: "{{apacheds_server_port}}"

