---
installer_user: "ubuntu"
hosting_userpass: ""
services_host: "localhost"
use_secure_http: false
use_custom_ssl_certificates: false
custom_ssl_certificates_path:
certificate_crt_filename: "self-signed-certificate.crt"
certificate_key_filename: "self-signed-certificate.key"
keystore_password: "changeme"
hspc_platform_jwt_key: "changeme"
aws_output_format: "json"
aws_region: "changeme"
aws_access_key_id: "changeme"
aws_secret_access_key: "changeme"
aws_ec2_volume_id: "changeme"
enable_backup_restore_jobs: false
enable_aws_snapshot: false
enable_pwm: false
mysql_host: "localhost"
mysql_root_pass: "password"
mysql_password: "password"
email_account_description: "SMART Account Services"
email_smtp_address: "changeme"
email_smtp_port: "587"
email_smtp_username: "changeme"
email_smtp_password_encrypted: "changeme"
email_admin_address: "admin@example.com"
email_contact_addresss: "contact@example.com"
apacheds_server_external_host: "{{services_host}}"
apacheds_server_system_admin_password: "secret"
apacheds_server_sandbox_admin_password: "password"
apacheds_server_installer_enabled: true
pwm_server_external_host: "{{services_host}}"
pwm_server_external_port: "9092"
pwm_unlocked: true
pwm_configpasswordhash: "changeme"
pwm_securitykey_encrypted: "changeme"
pwm_db_password_encrypted: "changeme"
pwm_sso_authentication_header_name: "changeme"
pwm_ldap_proxy_password_encrypted: "changeme"
auth_server_external_host: "{{services_host}}"
auth_server_external_port: "9060"
auth_server_initial_memory: "32M"
auth_server_max_memory: "128M"
auth_server_newUserUrl: "{{pwm_server_external_url}}public/newuser"
auth_server_forgotPasswordUrl: "{{pwm_server_external_url}}public/forgottenpassword"
auth_server_admin_password: "password"
auth_mysql_reset_database: false
api_server_oauth2_clientId: "hspc_resource_server"
api_server_oauth2_clientSecret: "secret"
enable_api_sample_data: true
enable_mock_endpoints: false
api_dstu2_server_external_host: "{{services_host}}"
api_dstu2_server_external_port: "9071"
api_dstu2_server_initial_memory: "128M"
api_dstu2_server_max_memory: "256M"
api_dstu2_mysql_reset_database: false
api_dstu2_sample_patients_limit: "20"
mock_api_dstu2_server_external_host: "{{services_host}}"
mock_api_dstu2_server_external_port: "9271"
mock_api_dstu2_server_initial_memory: "128M"
mock_api_dstu2_server_max_memory: "256M"
api_stu3_server_external_host: "{{services_host}}"
api_stu3_server_external_port: "9074"
api_stu3_server_initial_memory: "128M"
api_stu3_server_max_memory: "256M"
api_stu3_mysql_reset_database: false
api_stu3_sample_patients_limit: "20"
mock_api_stu3_server_external_host: "{{services_host}}"
mock_api_stu3_server_external_port: "9274"
mock_api_stu3_server_initial_memory: "128M"
mock_api_stu3_server_max_memory: "256M"
messaging_server_external_host: "localhost"
messaging_server_external_port: "8091"
messaging_server_initial_memory: "32M"
messaging_server_max_memory: "64M"
messaging_profiles: "test"
sandman_server_artifact_version: "2.0.0"
sandman_server_artifact_repository_url: "{{release_repository_url}}"
sandman_server_external_host: "{{services_host}}"
sandman_server_external_port: "9080"
sandman_server_initial_memory: "16M"
sandman_server_max_memory: "128M"
sandman_server_send_email: false
sandbox_server_admin_access_client_secret: "changeme"
sandman_server_external_host: "{{services_host}}"
sandman_server_api_v1_url: "{{api_dstu2_server_external_url}}"
sandman_server_api_v2_url: "{{api_stu3_server_external_url}}"
sandman_server_api_v3_url: "{{api_stu3_server_external_url}}"
sandman_server_api_v4_url: "{{api_stu3_server_external_url}}"
account_server_external_url: "{{pwm_server_external_url}}"
sandman_mysql_reset_database: false
sandman_server_external_port: "9080"
sandman_api_server_artifact_version: "0.1.2"
sandman_api_server_artifact_repository_url: "{{release_repository_url}}"
sandman_api_server_external_host: "{{services_host}}"
sandman_api_server_external_port: "13000"
sandman_api_server_initial_memory: "128M"
sandman_api_server_max_memory: "256M"
sandman_api_server_send_email: false
sandman_api_mysql_database_drop: true
sandman_api_server_api_v1_url: "{{api_dstu2_server_external_url}}"
sandman_api_server_api_v2_url: "{{api_stu3_server_external_url}}"
sandman_api_server_api_v3_url: "{{api_stu3_server_external_url}}"
sandman_api_server_api_v4_url: "{{api_stu3_server_external_url}}"
apps_server_external_host: "{{services_host}}"
apps_server_external_port: "9093"
patient_picker_server_external_host: "{{apps_server_external_host}}"
patient_picker_server_external_port: "{{apps_server_external_port}}"
