---
pwm_server_initial_memory: 128M
pwm_server_max_memory: 256M

# Version control information
pwm_branch: "master"
pwm_project: "pwm"

# Database schema
pwm_server_database: pwm

# Tomcat settings
tomcat_version: 8.5.11
tomcat_artifact_name: "apache-tomcat-{{tomcat_version}}"
tomcat_home: "{{install_dir}}/{{tomcat_artifact_name}}"
tomcat_artifact_host: "http://mirror.metrocast.net/apache/tomcat/tomcat-8/v{{tomcat_version}}/bin"
tomcat_artifact_url: "{{tomcat_artifact_host}}/{{tomcat_artifact_name}}.tar.gz"
tomcat_shutdown_port: 8005
tomcat_redirect_port: 8443
tomcat_ajp_port: 8009
tomcat_server_name: Catalina
tomcat_default_host: localhost

pwm_unlocked: false
pwm_configpasswordhash: $2a$10$02soH2RZk9WEi3eYcv3h2.sP8eHEyzXw/k6TaUpJkT2v9CcPssA52
pwm_securitykey_encrypted: DlybqwJ9yN2wYi1ywaqZDGMEVp3WzCow/TMyVKNxAxclbKlBCl/OcAcXAP1xNhtF060jCPD0dfptWzjW2c/kIKf6o/iemTKGnRNDF11UmfCzAesx5CGplI+2StSmvkGl/bmWXTQc+L9xNUPrRdgVNQJVzXvfIaOy8xTTx6s6nPqhOCYnPfuEXKMTSEJo9nXvIEGWurVSRFtCPV/L9QF8YKjuUWvWiA0Ftc/S0dG8FJQ85ohlFsttThUcZ0cf4OswG3EY2oQjlMfNE0RFxe312Tr2F+bcB8UBlb+58TCQe/pOlpABc580yoWkvtTKcxO0zfkeYHIMtGfMZL2Ve6XzHFUODX9/PeZUUhFbjXx99lVzG6ypXautFYKbWmMpc2addjuiH1IEIO7wADREsYcTREtkWjOd5xk8ksB+wX/4zoUPFKCdJ2Pw8oLc6Pm9XQjiU+WEUvcpWWzgha0K2LeCSR2HQeCfu6x62cQgYVQDGawzEvZ5KWdvrBOvfi0jz7ZFmDek3ozmVqWColdkej42Jqhf4rHNjI99AdRvdHUaTatUIf38kNSKVl0v5Vq9mdjYfm+RSvYW3AJooEUSV2MfVM65t7WTSqS+YP6SZZGruHsnG0qJYQNqswfycI6pJhBr3M7WH1VOG13qx3+uXXD9811CTcwoI2Su6kAyNg/0VhEfD9pvaTKzNT0FC+8rODPjcfcBSC3NvLCalCSBTtB4f+UP6pVhRNAVMQ11bR4usVtk9XG2AWAVZQj7aBPtAReOxOfFyCiRtHOiB5wPYM7pnWHTjNMWC/kPaHZnV+yNWgqebAbZGQif7v9PpKjAQWq24b8z1Z9Zn+XHQA8Cm3le7xu7pzQ+WMS9NXBy+CgSpjxPVVlqUxIGUe2SM2oMWq0SrxPxLwpZAXooB+47N/tRKiy8nofTG3FvRktY4U88K1G/8HmPpA/Xix+lzNOM5JYN81dSWa7yBAopORdp+DF7yTuQeAJamh+DoMy6R/vUgdOfntmglaSh8OAlacn16oi6hNdmFEQ9FYNxscRtesEee82r5w2Tf7PxE6zWT9McIlj1wTUxya0AKp/+HAQrWuEeVbZVJmvqlgitWZmFL0SL6pFNwGibXb8T3dxieX2xm0AMSyteIu7x1G+aNBo3DccyOo+Yp34nN4cC5LmonrCEDI6vD0U3RhGX+NSgTrjWQwUlDmjORcc3N+X6dUZLNVchSEG49c/oZVwXd8WRYH/NvBgJQY/11qGsBOgNBCR8hGwEqwMmIZBzrGyPFpVxbj+hRJGz7AQfNp+AtUX5fN7rHeEbNNYIOH3T+Usmv7NyfNpZqQjzZfBtd0kKH11G0wfwzxj1TcrQXtwayUOD8sSWhXraKH398+GAKyMYC/y+auk=
pwm_db_password_encrypted: gDs7KkJA/xJ6oFT56C2dRA==
pwm_sso_authentication_header_name: c8381465-a7f8-4ecc-958d-ec296d6e8671
pwm_ldap_proxy_password_encrypted: gDs7KkJA/xJ6oFT56C2dRA==
pwm_i18n_display_name: SMART Health IT Account Self Service
